Exclude `vendor` from rubocop
To prevent failures like these:
```
Error: The `Metrics/LineLength` cop has been moved to `Layout/LineLength`.
(obsolete configuration found in vendor/bundle/ruby/3.4.0/gems/android_key_attestation-0.3.0/.rubocop.yml, please update it)
The `Style/UnneededInterpolation` cop has been renamed to `Style/RedundantInterpolation`.
(obsolete configuration found in vendor/bundle/ruby/3.4.0/gems/android_key_attestation-0.3.0/.rubocop.yml, please update it)
The `Style/UnneededPercentQ` cop has been renamed to `Style/RedundantPercentQ`.
(obsolete configuration found in vendor/bundle/ruby/3.4.0/gems/android_key_attestation-0.3.0/.rubocop.yml, please update it)
The `Style/BracesAroundHashParameters` cop has been removed. Please use  and/or  instead.
(obsolete configuration found in vendor/bundle/ruby/3.4.0/gems/android_key_attestation-0.3.0/.rubocop.yml, please update it)
```