Add step to remove `Gemfile.lock`
To prevent:
```
  ERROR:  Error installing bundler:
  	bundler-2.7.1 requires Ruby version >= 3.2.0. The current ruby version is 3.1.7.
```
when testing against ruby 3.1