ci: load :active_job for combustion app
For some reason, tests are failing if we do not include it:

```
Failures:

  1) Devise::PasskeysController POST #create when user is authenticated with valid parameters creates a new passkey and redirects
     Failure/Error:
       assert_difference("user.passkeys.count", 1) do
         post user_passkeys_path, params: {
           public_key_credential: credential.to_json,
           name: "My Passkey"
         }
       end

     NoMethodError:
       undefined method 'assert_difference' for #<RSpec::ExampleGroups::DevisePasskeysController::POSTCreate::WhenUserIsAuthenticated::WithValidParameters:0x0000000122093800>
     # /Users/santiago_rodriguez/.gem/ruby/3.4.4/gems/railties-8.0.2.1/lib/rails/engine/lazy_route_set.rb:99:in 'method_missing'
     # /Users/santiago_rodriguez/.gem/ruby/3.4.4/gems/activerecord-8.0.2.1/lib/active_record/test_fixtures.rb:280:in 'ActiveRecord::TestFixtures#method_missing'
     # /Users/santiago_rodriguez/.gem/ruby/3.4.4/gems/actionpack-8.0.2.1/lib/action_dispatch/testing/assertions/routing.rb:269:in 'ActionDispatch::Assertions::RoutingAssertions#method_missing'
     # /Users/santiago_rodriguez/.gem/ruby/3.4.4/gems/actionpack-8.0.2.1/lib/action_dispatch/testing/integration.rb:448:in 'ActionDispatch::Integration::Runner#method_missing'
     # ./spec/requests/devise/passkeys_controller_spec.rb:46:in 'block (5 levels) in <top (required)>'
```

Let's include it for now and try to dig in to what's going on later.